{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlr3inferr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mlr3inferr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mlr3inferr/mlr3inferr_{{ version }}.tar.gz
  sha256: 956afcd42245caaed85b9f515f422fc22e3085e99b1ab50fcd51314852508033

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-checkmate
    - r-data.table
    - r-future
    - r-lgr
    - r-mlr3
    - r-mlr3measures
    - r-mlr3misc
    - r-paradox
    - r-withr
  run:
    - r-base
    - r-r6
    - r-checkmate
    - r-data.table
    - r-future
    - r-lgr
    - r-mlr3
    - r-mlr3measures
    - r-mlr3misc
    - r-paradox
    - r-withr

test:
  commands:
    - $R -e "library('mlr3inferr')"           # [not win]
    - "\"%R%\" -e \"library('mlr3inferr')\""  # [win]

about:
  home: https://mlr3inferr.mlr-org.com, https://github.com/mlr-org/mlr3inferr
  license: LGPL-3.0-only
  summary: An 'mlr3' extension that provides various resampling-based confidence interval (CI)
    methods for estimating the generalization error.  These CI methods are implemented
    as 'mlr3' measures, enabling the evaluation of individual algorithms on specific
    tasks as well as the comparison of different learning algorithms.
  license_family: LGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
